# Generated by Django 5.1.11 on 2025-10-01 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Petition",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("movie_name", models.CharField(max_length=255, unique=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_petitions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "signers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="signed_petitions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
